export enum Route {
    HOME = '/',
    PROFILE = '/profile',
    MYNFT = '/mynft',
    PATENT = '/mynft/:id',
    NFT_DETAIL = '/nft/detail/:ipfsHash',
    ACCOUNT_EDIT = '/account/edit',
    ADMIN_DASHBOARD = '/admin/dashboard',
    ADMIN_USERS = '/admin/users',
    LOGIN = '/login',
    SIGNOUT = '/signout',
    SIGNUP = '/signup/:id',
    FORGOT_PASSWORD = '/forgot_password',
    BUY_NFT='/nft/:owner/:id',
    COLLECTABLES_DETAIL = '/nft/collectable/detail/:owner/:id/:assetIndexHash',
}